apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teamtalk-server-dpl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: teamtalk-server
    spec:
      containers:
        - name: teamtalk-server
          image: plequen/teamtalk-server
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 256Mi
              cpu: 0.1
            requests:
              memory: 256Mi
              cpu: 0.1