# A headless service to create DNS records
# ! targetPort must equal port
apiVersion: v1
kind: Service
metadata:
  name: teamtalk-server-svc
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: teamtalk-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: teamtalk-server